'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import type {Table} from '@/lib/table';

type Rig={hand:THREE.Group;head:THREE.Group;shoulder:THREE.Vector3;upper:THREE.Mesh;lower:THREE.Mesh;camera:THREE.OrthographicCamera;renderer:THREE.WebGLRenderer;scene:THREE.Scene};
function limb(mesh:THREE.Mesh,a:THREE.Vector3,b:THREE.Vector3){mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.scale.set(1,a.distanceTo(b),1);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());}
export default function Dealer({table,motion,onBusy}:{table:Table|null;motion:boolean;onBusy:(busy:boolean)=>void}){
 const host=useRef<HTMLDivElement>(null),rig=useRef<Rig|null>(null),seen=useRef(new Set<string>()),handTarget=useRef(new THREE.Vector3(-35,90,85)),[available,setAvailable]=useState(false),[failed,setFailed]=useState(false);
 useEffect(()=>{if(!host.current)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{setFailed(true);return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;host.current.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-500,500,350,-350,.1,3000);camera.position.set(0,0,1000);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xffead3,0x193a2d,2));const key=new THREE.DirectionalLight(0xffe5c2,3);key.position.set(-250,400,500);scene.add(key);const rim=new THREE.DirectionalLight(0xb8dfcb,2);rim.position.set(250,100,-200);scene.add(rim);
 const skin=new THREE.MeshStandardMaterial({color:0xbe8b69,roughness:.7}),shirt=new THREE.MeshStandardMaterial({color:0xe6e4d9,roughness:.8}),vest=new THREE.MeshStandardMaterial({color:0x15201e,roughness:.8}),hair=new THREE.MeshStandardMaterial({color:0x281d19,roughness:1}),black=new THREE.MeshStandardMaterial({color:0x151712,roughness:.4});
 function oval(parent:THREE.Object3D,mat:THREE.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number){const m=new THREE.Mesh(new THREE.SphereGeometry(1,32,24),mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);parent.add(m);return m;}
 const person=new THREE.Group();scene.add(person);oval(person,shirt,0,169,-12,106,100,35);oval(person,vest,0,150,15,82,86,28);oval(person,skin,0,239,3,19,30,18);
 const head=new THREE.Group();head.position.set(0,290,13);person.add(head);oval(head,skin,0,0,0,36,47,31);oval(head,hair,0,22,-5,37,29,31);oval(head,skin,-36,-2,0,6,13,8);oval(head,skin,36,-2,0,6,13,8);oval(head,skin,0,-3,30,7,12,8);for(const x of [-14,14]){oval(head,shirt,x,7,29,7,4,3);oval(head,black,x,7,32,2.3,2.8,1.5);oval(head,hair,x,16,28,9,2,2);}oval(head,new THREE.MeshStandardMaterial({color:0x774e40}),0,-22,28,12,2,2);
 // Shirt collar, bow tie and vest buttons.
 for(const x of [-15,15]){const collar=new THREE.Mesh(new THREE.ConeGeometry(14,30,3),shirt);collar.position.set(x,231,37);collar.rotation.z=x<0?-.5:.5;person.add(collar);oval(person,black,x/2,214,46,12,8,5);}for(let y=125;y<205;y+=22)oval(person,black,0,y,43,3,3,2);
 const upper=new THREE.Mesh(new THREE.CylinderGeometry(16,14,1,20),shirt),lower=new THREE.Mesh(new THREE.CylinderGeometry(13,10,1,20),shirt);scene.add(upper,lower);const shoulder=new THREE.Vector3(84,183,0),hand=new THREE.Group();scene.add(hand);oval(hand,skin,0,0,0,17,10,10);for(let i=0;i<4;i++)oval(hand,skin,-11+i*7,-12,3,3,14-i,3);oval(hand,skin,-18,0,4,4,12,4);
 const leftUpper=new THREE.Mesh(new THREE.CylinderGeometry(16,14,1,20),shirt),leftLower=new THREE.Mesh(new THREE.CylinderGeometry(13,10,1,20),shirt);scene.add(leftUpper,leftLower);limb(leftUpper,new THREE.Vector3(-84,183,0),new THREE.Vector3(-107,112,35));limb(leftLower,new THREE.Vector3(-107,112,35),new THREE.Vector3(-55,83,85));oval(scene,skin,-55,83,85,20,11,10);
 const pack=new THREE.Mesh(new THREE.BoxGeometry(27,9,42),new THREE.MeshStandardMaterial({color:0xd3ddbd,roughness:.6}));pack.position.set(-49,87,98);pack.rotation.x=.3;scene.add(pack);
 const value={hand,head,shoulder,upper,lower,camera,renderer,scene};rig.current=value;setAvailable(true);const resize=()=>{if(host.current)renderer.setSize(host.current.clientWidth,host.current.clientHeight,false)};const observer=new ResizeObserver(resize);observer.observe(host.current);resize();let frame=0;let disposed=false;const loop=()=>{if(disposed)return;const target=handTarget.current;hand.position.copy(target);const elbow=new THREE.Vector3(130,110,30).lerp(target.clone().add(new THREE.Vector3(40,45,-20)),.35);limb(upper,shoulder,elbow);limb(lower,elbow,target);head.rotation.y=target.x/800;renderer.render(scene,camera);frame=requestAnimationFrame(loop)};loop();return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();rig.current=null;scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove();};
 },[]);
 useEffect(()=>{if(!host.current)return;const room=host.current.parentElement!;const all=[...room.querySelectorAll<HTMLElement>('[data-deal-card]')];if(!table){seen.current.clear();onBusy(false);return;}if(!available&&!failed){all.filter(el=>!seen.current.has(el.dataset.dealCard!)).forEach(el=>el.style.visibility='hidden');onBusy(true);return;}const fresh=all.filter(el=>!seen.current.has(el.dataset.dealCard!));fresh.sort((a,b)=>Number(a.dataset.dealOrder)-Number(b.dataset.dealOrder));fresh.forEach(el=>seen.current.add(el.dataset.dealCard!));if(!fresh.length){onBusy(false);return;}if(!motion||failed){fresh.forEach(el=>el.style.visibility='');onBusy(false);return;}
 fresh.forEach(el=>el.style.visibility='hidden');onBusy(true);let frame=0,ghost:HTMLElement|null=null,index=0,start=performance.now(),stopped=false;const rest=new THREE.Vector3(-35,90,85);const step=(now:number)=>{if(stopped)return;const el=fresh[index],r=rig.current;if(!el||!r){fresh.forEach(c=>c.style.visibility='');handTarget.current.copy(rest);onBusy(false);return;}const bounds=room.getBoundingClientRect(),dest=el.getBoundingClientRect(),targetX=(dest.left+dest.width/2-bounds.left)/bounds.width*1000-500;const release=new THREE.Vector3(targetX*.3,65,120),t=Math.min(1,(now-start)/620);if(!ghost){ghost=el.cloneNode(true) as HTMLElement;ghost.removeAttribute('data-deal-card');ghost.classList.add('dealer-flying-card');ghost.style.cssText=`position:absolute;left:0;top:0;width:${dest.width}px;height:${dest.height}px;visibility:visible;animation:none;margin:0;z-index:12;pointer-events:none;`;room.appendChild(ghost);}
 const reach=Math.sin(Math.min(1,t/.48)*Math.PI/2);handTarget.current.copy(rest).lerp(release,t<.48?reach:Math.max(0,1-(t-.48)/.52));const projection=(t<.48?handTarget.current:release).clone().project(r.camera);const fromX=(projection.x+1)/2*bounds.width,fromY=(1-projection.y)/2*bounds.height;const flight=Math.max(0,(t-.48)/.52),ease=1-(1-flight)**2;const toX=dest.left+dest.width/2-bounds.left,toY=dest.top+dest.height/2-bounds.top;const x=fromX+(toX-fromX)*ease,y=fromY+(toY-fromY)*ease-Math.sin(flight*Math.PI)*25;ghost.style.transform=`translate(${x-dest.width/2}px,${y-dest.height/2}px) scale(${.52+.48*ease}) rotate(${(1-ease)*-12}deg)`;
 if(t>=1){el.style.visibility='';ghost.remove();ghost=null;index++;start=now;if(index>=fresh.length){handTarget.current.copy(rest);onBusy(false);return;}}frame=requestAnimationFrame(step)};frame=requestAnimationFrame(step);return()=>{stopped=true;cancelAnimationFrame(frame);ghost?.remove();fresh.forEach(el=>el.style.visibility='');handTarget.current.copy(rest);};
 },[table?.number,table?.board.length,motion,available,failed,onBusy]);
 return <><div ref={host} className="dealer-3d" aria-hidden="true"/><div className="dealer-caption"><span>{failed?'STANDARD DEAL · 3D UNAVAILABLE':'3D DEALER · INTERACTIVE PROTOTYPE'}</span></div></>;
}
