import {deck,rankHand} from './poker.ts';
export type Table={number:number;button:number;hands:string[][];board:string[];shoe:string[];stacks:number[];bets:number[];pot:number;street:number;turn:number;acted:boolean[];minRaise:number;done:boolean;message:string;log:string[]};
export const streets=['Preflop','Flop','Turn','River'];
export function deal(previous?:Table):Table{if(previous&&!previous.done)throw Error('Finish this hand first.');const shoe=[...deck];for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shoe[i],shoe[j]]=[shoe[j],shoe[i]];}const button=previous?1-previous.button:0;const stacks=previous?[...previous.stacks]:[1000,1000];if(stacks.some(s=>s<=0))throw Error('Reset the practice session to refill chips.');const s:Table={number:(previous?.number||0)+1,button,hands:[[shoe.pop()!,shoe.pop()!],[shoe.pop()!,shoe.pop()!]],board:[],shoe,stacks,bets:[0,0],pot:0,street:0,turn:button,acted:[false,false],minRaise:10,done:false,message:'',log:[]};for(const p of [button,1-button]){const amount=Math.min(p===button?5:10,s.stacks[p]);s.stacks[p]-=amount;s.bets[p]=amount;s.pot+=amount;}s.log.push('Blinds posted: 5 / 10.');if(s.stacks.some(x=>x===0)&&s.bets[0]===s.bets[1])showdown(s);return s;}
function showdown(s:Table){const excess=Math.abs(s.bets[0]-s.bets[1]);if(excess){const p=s.bets[0]>s.bets[1]?0:1;s.stacks[p]+=excess;s.pot-=excess;s.bets[p]-=excess;}while(s.board.length<5)s.board.push(s.shoe.pop()!);const a=rankHand([...s.hands[0],...s.board]),b=rankHand([...s.hands[1],...s.board]);s.done=true;s.street=3;if(a===b){s.stacks[0]+=Math.floor(s.pot/2);s.stacks[1]+=Math.floor(s.pot/2);s.stacks[1-s.button]+=s.pot%2;s.message=`Split pot: ${s.pot} practice chips.`;}else{const p=a>b?0:1;s.stacks[p]+=s.pot;s.message=`${p===0?'You win':'Opponent wins'} ${s.pot} practice chips at showdown.`;}s.log.push(s.message);}
export function limits(s:Table,p=s.turn){const call=Math.max(0,s.bets[1-p]-s.bets[p]);const max=Math.min(s.bets[p]+s.stacks[p],s.bets[1-p]+s.stacks[1-p]);return {call,max,min:Math.max(...s.bets)+s.minRaise,canRaise:s.stacks[1-p]>0&&max>Math.max(...s.bets)};}
export function act(state:Table,action:'fold'|'check'|'call'|'raise',total?:number):Table{if(state.done)throw Error('This hand is complete.');const s=structuredClone(state),p=s.turn,o=1-p,l=limits(s),name=p===0?'You':'Opponent';if(action==='fold'){s.stacks[o]+=s.pot;s.done=true;s.message=`${name} folded. ${o===0?'You win':'Opponent wins'} ${s.pot} practice chips.`;s.log.push(s.message);return s;}
 if(action==='check'&&l.call>0)throw Error('Face a bet: call, raise or fold.');if(action==='call'&&l.call===0)throw Error('No bet to call.');
 if(action==='raise'){if(!l.canRaise||!Number.isInteger(total)||total!<=Math.max(...s.bets)||total!>l.max||(total!<l.min&&total!==l.max))throw Error('Choose a legal raise total.');const high=Math.max(...s.bets),amount=total!-s.bets[p];s.stacks[p]-=amount;s.bets[p]=total!;s.pot+=amount;s.minRaise=Math.max(s.minRaise,total!-high);s.acted=[false,false];s.log.push(`${name} ${high?'raise':'bet'} to ${total}.`);}else if(action==='call'){const amount=Math.min(l.call,s.stacks[p]);s.stacks[p]-=amount;s.bets[p]+=amount;s.pot+=amount;s.log.push(`${name} call ${amount}.`);}else s.log.push(`${name} check.`);
 s.acted[p]=true;s.turn=o;
 if(s.stacks.some(x=>x===0)&&s.bets[p]<=s.bets[o]&&(action==='call'||s.bets[0]===s.bets[1])){showdown(s);return s;}
 if(s.acted.every(Boolean)&&s.bets[0]===s.bets[1]){if(s.street===3){showdown(s);return s;}s.street++;const n=s.street===1?3:1;for(let i=0;i<n;i++)s.board.push(s.shoe.pop()!);s.bets=[0,0];s.acted=[false,false];s.minRaise=10;s.turn=1-s.button;s.log.push(streets[s.street]+': '+s.board.join(' '));}
 return s;
}
export function botAction(s:Table):Table{const l=limits(s);const ranks='23456789TJQKA';const strength=s.street===0?(ranks.indexOf(s.hands[1][0][0])+ranks.indexOf(s.hands[1][1][0]))/24:(Math.floor(rankHand([...s.hands[1],...s.board])/15**5)+1)/5;const r=Math.random();if(l.call&&r>.65+Math.min(.25,strength/4))return act(s,'fold');if(l.canRaise&&r<.16&&l.max>=l.min)return act(s,'raise',Math.min(l.max,Math.max(l.min,Math.max(...s.bets)+Math.floor(s.pot/2))));return act(s,l.call?'call':'check');}
