import {deck,rankHand} from './poker.ts';
export type Table={number:number;button:number;sb:number;bb:number;hands:string[][];board:string[];shoe:string[];stacks:number[];bets:number[];paid:number[];folded:boolean[];pot:number;street:number;turn:number;acted:boolean[];raiseAt:number[];minRaise:number;done:boolean;showdown:boolean;message:string;log:string[];last:string[];awards:number[]};
export const streets=['Preflop','Flop','Turn','River'];
export const names=['You','Alex','Maya','Leo','Sofia','Max'];
function next(s:Table,p:number,eligible=(i:number)=>!s.folded[i]&&s.stacks[i]>0){for(let k=1;k<=s.stacks.length;k++){const i=(p+k)%s.stacks.length;if(eligible(i))return i;}return -1;}
function pay(s:Table,p:number,n:number){s.stacks[p]-=n;s.bets[p]+=n;s.paid[p]+=n;s.pot+=n;}
export function deal(previous?:Table,count=2):Table{if(previous&&!previous.done)throw Error('Finish this hand first.');if(!Number.isInteger(count)||count<2||count>6)throw Error('Choose 2 to 6 players.');const stacks=previous?[...previous.stacks]:Array(count).fill(1000),n=stacks.length;if(stacks.filter(x=>x>0).length<2||stacks[0]===0)throw Error('Reset the practice session to refill chips.');const shoe=[...deck];for(let i=51;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shoe[i],shoe[j]]=[shoe[j],shoe[i]];}const s:Table={number:(previous?.number||0)+1,button:0,sb:0,bb:1,hands:Array.from({length:n},()=>[]),board:[],shoe,stacks,bets:Array(n).fill(0),paid:Array(n).fill(0),folded:stacks.map(x=>x===0),pot:0,street:0,turn:0,acted:Array(n).fill(false),raiseAt:Array(n).fill(-1),minRaise:10,done:false,showdown:false,message:'',log:[],last:Array(n).fill(''),awards:Array(n).fill(0)};s.button=previous?next(s,previous.button):0;s.sb=stacks.filter(x=>x>0).length===2?s.button:next(s,s.button);s.bb=next(s,s.sb);for(let round=0;round<2;round++){let p=s.button;for(let i=0;i<stacks.filter(x=>x>0).length;i++){p=next(s,p);s.hands[p].push(s.shoe.pop()!);}}for(const p of [s.sb,s.bb]){const amount=Math.min(p===s.sb?5:10,s.stacks[p]);pay(s,p,amount);s.last[p]=`${p===s.sb?'SB':'BB'} ${amount}`;}s.turn=next(s,s.bb);s.log.push(`Hand ${s.number} · ${names[s.button]} on the button. Blinds 5 / 10.`);settle(s,s.bb);return s;}
export function limits(s:Table,p=s.turn){const high=Math.max(...s.bets),call=Math.max(0,high-s.bets[p]),max=s.bets[p]+s.stacks[p];const reopened=!s.acted[p]||high-s.raiseAt[p]>=s.minRaise;return {call,max,min:high+s.minRaise,canRaise:!s.done&&!s.folded[p]&&s.stacks.some((x,i)=>i!==p&&!s.folded[i]&&x>0)&&max>high&&reopened};}
function finish(s:Table){s.showdown=true;while(s.board.length<5)s.board.push(s.shoe.pop()!);s.street=3;const levels=[...new Set(s.paid.filter(x=>x>0))].sort((a,b)=>a-b);let previous=0;for(const level of levels){const contributors=s.paid.map((v,i)=>v>=level?i:-1).filter(i=>i>=0),amount=(level-previous)*contributors.length;previous=level;if(contributors.length===1){s.awards[contributors[0]]+=amount;continue;}const eligible=contributors.filter(i=>!s.folded[i]);if(!eligible.length)throw Error('Invalid pot: no eligible player.');const ranks=eligible.map(i=>rankHand([...s.hands[i],...s.board])),best=Math.max(...ranks),winners=eligible.filter((_,i)=>ranks[i]===best);const share=Math.floor(amount/winners.length);winners.forEach(i=>s.awards[i]+=share);let remainder=amount%winners.length;for(let k=1;k<=s.stacks.length&&remainder;k++){const i=(s.button+k)%s.stacks.length;if(winners.includes(i)){s.awards[i]++;remainder--;}}}s.awards.forEach((a,i)=>s.stacks[i]+=a);s.done=true;s.message=s.awards.map((a,i)=>a?`${names[i]} receives ${a}`:'').filter(Boolean).join(' · ')+ ' chips.';s.log.push('Showdown: '+s.message);}
function settle(s:Table,after:number){const alive=s.folded.map((f,i)=>!f?i:-1).filter(i=>i>=0);if(alive.length===1){s.done=true;s.awards[alive[0]]=s.pot;s.stacks[alive[0]]+=s.pot;s.message=`${names[alive[0]]} wins ${s.pot} chips. Everyone else folded.`;s.log.push(s.message);return;}const can=alive.filter(i=>s.stacks[i]>0),high=Math.max(...s.bets);if(can.length===0||(can.length===1&&s.bets[can[0]]>=high)){finish(s);return;}const closed=can.every(i=>s.acted[i]&&s.bets[i]===high);if(closed){if(s.street===3){finish(s);return;}s.street++;for(let i=0;i<(s.street===1?3:1);i++)s.board.push(s.shoe.pop()!);s.bets.fill(0);s.acted.fill(false);s.raiseAt.fill(-1);s.last.fill('');s.minRaise=10;s.turn=next(s,s.button);s.log.push(streets[s.street]+': '+s.board.join(' '));}else s.turn=next(s,after,i=>!s.folded[i]&&s.stacks[i]>0&&(!s.acted[i]||s.bets[i]<high));}
export function act(state:Table,action:'fold'|'check'|'call'|'raise',total?:number):Table{if(state.done)throw Error('This hand is complete.');const s=structuredClone(state),p=s.turn,l=limits(s);if(p<0||s.folded[p]||s.stacks[p]===0)throw Error('This seat cannot act.');if(action==='check'&&l.call>0)throw Error('Face a bet: call, raise or fold.');if(action==='call'&&l.call===0)throw Error('No bet to call.');if(action==='fold'){s.folded[p]=true;s.last[p]='Fold';}else if(action==='raise'){const high=Math.max(...s.bets);if(!l.canRaise||!Number.isInteger(total)||total!<=high||total!>l.max||(total!<l.min&&total!==l.max))throw Error(`Choose a total from ${Math.min(l.min,l.max)} to ${l.max}.`);pay(s,p,total!-s.bets[p]);if(total!-high>=s.minRaise){s.minRaise=total!-high;s.acted.fill(false);s.raiseAt.fill(-1);}s.last[p]=`${high?'Raise':'Bet'} ${total}`;}else if(action==='call'){const amount=Math.min(l.call,s.stacks[p]);pay(s,p,amount);s.last[p]=`Call ${amount}`;}else s.last[p]='Check';if(s.stacks[p]===0)s.last[p]+=' · All-in';s.log.push(`${names[p]}: ${s.last[p]}.`);s.acted[p]=true;s.raiseAt[p]=Math.max(...s.bets);settle(s,p);return s;}
export function botAction(s:Table):Table{if(s.turn===0||s.done)throw Error('Not an opponent turn.');const p=s.turn,l=limits(s),ranks='23456789TJQKA',h=s.hands[p];const strength=s.street===0?(ranks.indexOf(h[0][0])+ranks.indexOf(h[1][0]))/24:(Math.floor(rankHand([...h,...s.board])/15**5)+1)/5;const r=Math.random(),pressure=l.call/Math.max(1,s.pot);if(l.call&&r>.72+Math.min(.2,strength/4)-Math.min(.2,pressure/3))return act(s,'fold');if(l.canRaise&&r<.12&&l.max>=l.min)return act(s,'raise',Math.min(l.max,Math.max(l.min,Math.max(...s.bets)+Math.floor(s.pot/2))));return act(s,l.call?'call':'check');}
